%% Import data from text file
clc,clear,close
% Script for importing data from the following text file:
%
%    filename: \\userMN\N\nguy0936\Desktop\raw_sleep-monitor_respiratory-rate.csv
%
% Auto-generated by MATLAB on 26-Feb-2021 11:12:16
warning('off','all')
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["start", "duration", "value"];
opts.VariableTypes = ["string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["start", "duration", "value"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["start", "duration", "value"], "EmptyFieldRule", "auto");

% Import the data
rawsleepmonitorrespiratoryrate = readtable("raw_sleep-monitor_respiratory-rate.csv", opts);


%% Clear temporary variables
clear opts
data = rawsleepmonitorrespiratoryrate;


%%

for i=1: size(data,1)

    d = data.start(i);
    datepart = extractBefore(d,"T"); % extract date
    timepart = extractBetween(d,"T","+"); % extract time

    datestring = append(datepart," ", timepart); % combine string
    d2 = datetime(datestring,'InputFormat','yyyy-MM-dd HH:mm:ss'); % convert to datetime

    data.date(i) = d2;
end

data.day = data.date.Day;
data.month = data.date.Month;
data.year = data.date.Year;

%%
clc
%newdata =table();
VALUE = [];
k = 1;
for month = 1:12
    
    
    for day = 1:31
        
      index = find (data.day==day & data.month==month);
      value_comb = [];
      if ~isempty(index)
          
          VALUE{k,1} = day;
          VALUE{k,2} = month;
          value_string = data.value(index);
          for j=1:length(value_string)
            value_comb = [value_comb  str2num( extractBetween(value_string(j),"[", "]") )];
          end
          
          VALUE{k,3} = value_comb; % combine all values
          VALUE{k,4} = data.date(index(1));
          VALUE{k,5} = data.date(index(end));
          
          k = k+1;
      end
    end % end day
    
    
end % end month

%% Newtable
mytable = table();

for i=1:length(VALUE)
    
    st = VALUE{i,4};
    st.Format = 'yyyy-MM-dd';
    mytable.Date(i) = st;
    
    st.Format = 'HH:mm:ss';
    mytable.Start_time(i)  = st;
    
    ed = VALUE{i,5};
    ed.Format = 'HH:mm:ss';
    
    mytable.End_time(i) = ed;
    
    mytable.Mean(i) = mean(VALUE{i,3});
end


mytable



writetable(mytable,'mytable.txt','Delimiter',' ')  



